### ISSUE TITLE
Allow user to pass in `OnFlickedXDirection` and `OnCancel` listeners

### ISSUE THREAD

**Issue by c0state** [t-kurimura/flickabledialog#6]
Currently, it looks like the `OnFlickedXDirection` and `OnCancel` listeners must be implemented on the calling activity or fragment. This should ideally be enhanced so that an arbitrary listener that implements this interface can be a listener.

**Comment by t-kurimura** [comment]
nice issue. I got this idea.I'll make `OnFlickedXDirection``OnCancel ` arbitrary implement method. it may take a little time for me to update.(a few weeks or so) I if possible, i'd like you to make pull-request.
Thank you.

**Comment by c0state** [comment]
Added via #7
