### ISSUE TITLE
question Implements on Activity not Fragment

### ISSUE THREAD

**Issue by renekaigen** [t-kurimura/flickabledialog#9]
How can I use the flickabledialog at Activity without Fragment?

**Comment by marcellsimon** [comment]
Same issue here

**Comment by t-kurimura** [comment]
I cannot figure out you intention... Do you mean that you don't want to use DialogFragment class or you want to call from Activity? it is unable if former and you should refer to [here](https://github.com/t-kurimura/flickabledialog#show) for latter.

**Comment by renesotolira** [comment]
Yes I want to call from activity. I  just read the new documentation , thank you
